services:
  budgy:
    container_name: budgy
    restart: unless-stopped
    build: .
    image: budgy
    networks:
      - nginxproxymanager_default
    ports:
      - "1300:1400"

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true